### ISSUE TITLE
Issue view is broken in Redmine version 3.2.0

### ISSUE THREAD

**Issue by sematro** [mrliptontea/PurpleMine2#21] opened 2015-12-14 13:28 UTC
I've upgraded my Redmine installation from 3.1.1 to 3.2.0. After the upgrade the display of issues was broken with the PurpleMine2 theme (see attachment).
I was able to reproduce this with a second installation.
![issue_3-1-1-vs-3-2-0](https://cloud.githubusercontent.com/assets/16189593/11782019/8e5d9158-a26e-11e5-9d85-0d44f9149076.png)

**Comment by kostajh** [comment] 2015-12-14 14:32
I'm seeing the same thing on Redmine 3.2.0. Thanks for all your work on this theme @mrliptontea!

**Comment by njrover** [comment] 2015-12-14 19:25
We were able to reproduce the same issue, it seems that the problem is that Redmine 3.2.0 uses div's for laying out the Issue while previous versions used tables.

**Comment by mrliptontea** [comment] 2015-12-14 22:25
Oh, that's actually good news, it seems the whole Redmine went responsive!
I will prepare some quick fix for this, but I see there's more changes that require attention.

**Closed** 2015-12-14 23:07 UTC
Labels: bug
