### ISSUE TITLE
Impossible to change repository branch nor tag in repository view

### ISSUE THREAD

**Issue by berturion** [mrliptontea/PurpleMine2#133] opened 2019-07-22 07:26 UTC
**Environment**
OS: Debian Stretch
Redmine version: 3.3.1.stable (debian stretch repository package)
Plugin Git active

**Problem**
When loading the page `repository`, javascript console shows the following error:

    ReferenceError: Raphael is not defined

It is impossible to change Git branch nor tag.

**Comment by mrliptontea** [comment] 2019-08-06 22:25
Hi,

I am unable to reproduce this, Raphael is a library that is normally included in Redmine for drawing graphs, so this isn't normal behaviour.

Can you post the full content of information from `/admin/info` page?
Also, try disabling adblock add-on in your browser if you have one?

**Comment by berturion** [comment] 2019-08-09 12:33
Hello,

```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Mercurial                      4.0
  Cvs                            1.12.13
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_image_clipboard_paste  3.3.0
```
With Chrome I see a `GET https://myserver.com/javascripts/raphael.js net::ERR_ABORTED 403 (Forbidden)` error.

I should check my apache2 web serveur config. Do you have any advice ?

**Comment by berturion** [comment] 2019-08-09 12:46
OK! I found the issue. I needed to install `libjs-raphael` package.
I don't understand why this wasn't not in the redmine dependencies. Maybe you could add this in your documentation?
Thanks.

**Comment by mrliptontea** [comment] 2019-08-10 17:10
Glad you found the cause.

However, it is not my theme's dependency, it is Redmine's, and normally it comes with Redmine already included.

In this case, the problem is with the Debian package and Raphael.js was clearly excluded from it: https://tracker.debian.org/media/packages/r/redmine/copyright-3.3.1-4deb9u2

I did some search and found that it was reported with this version and fixed in a newer version... Which is still unreleased. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=857952

**Closed by mrliptontea** 2019-08-10 17:10 UTC

**Comment by berturion** [comment] 2019-08-12 06:52
Ok, thank you :)
