### ISSUE TITLE
Graphical bug with redmine 4.2.3

### ISSUE THREAD

**Issue by momlamzombie** [mrliptontea/PurpleMine2#242] opened 2021-11-08 17:23 UTC
Hello,

When I used the theme with the branch 4.2.x of redmine, I have a graphical bug in issue view.

I have a shift between the selection and the results

![image](https://user-images.githubusercontent.com/29451738/140788421-b2955d20-f9ee-4f27-a7e5-2c7bf5558a63.png)

**Comment by dup2** [comment] 2022-01-10 10:44
Can confirm this on 4.2.3.stable also

**Comment by ivparamonov** [comment] 2022-01-21 11:48
The problem is due to the fact that in recent Redmine the `context-menu` element is inside the `content` div, so its top position is determined relative to the site header. I have fixed this issue by setting `position: fixed;` for the `context-menu` element.

**Comment by lbayerlein** [comment] 2022-06-23 08:12
Added a pull request: https://github.com/mrliptontea/PurpleMine2/pull/255

To fix this you have to add `#context-menu  { position: fixed !important }` to `redmine/public/themes/PurpleMine2/stylesheets/application.css`

**Comment by mrliptontea** [comment] 2023-05-15 20:38
Fixed by #262

**Closed by mrliptontea** 2023-05-15 20:38 UTC
